version: '3.3'

services:

  db:
    image: postgres:14-alpine
    restart: on-failure:5
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer:4
    restart: on-failure:5
    ports:
      - 8123:8080
